platform :ios, '6.1'

pod 'GMCAcknowledgements', :path => '..'

post_install do |installer|
    require 'fileutils'
    FileUtils.cp_r('Pods/Pods-acknowledgements.markdown', 'GMCAcknowledgementsDemo/Acknowledgements.markdown', :remove_destination => true)
end
